import type { Transaction } from "@/types/bank";

export const mockTransactions: Transaction[] = [
  // December 2025
  {
    id: "txn_001",
    date: "2025-12-05",
    description: "Nasi Lemak Antarabangsa",
    amount: 18.5,
    type: "debit",
    category: "food",
  },
  {
    id: "txn_002",
    date: "2025-12-04",
    description: "Starbucks KLCC",
    amount: 23.0,
    type: "debit",
    category: "food",
  },
  {
    id: "txn_003",
    date: "2025-12-04",
    description: "Shell Petrol Station",
    amount: 150.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_004",
    date: "2025-12-03",
    description: "TNB Electricity Bill",
    amount: 127.4,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_005",
    date: "2025-12-03",
    description: "Netflix Subscription",
    amount: 54.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_006",
    date: "2025-12-02",
    description: "Transfer from Sarah",
    amount: 250.0,
    type: "credit",
    category: "transfer",
    recipient: "Sarah",
  },
  {
    id: "txn_007",
    date: "2025-12-02",
    description: "Uniqlo Mid Valley",
    amount: 289.0,
    type: "debit",
    category: "shopping",
  },
  {
    id: "txn_008",
    date: "2025-12-01",
    description: "Salary December",
    amount: 8500.0,
    type: "credit",
    category: "income",
  },
  {
    id: "txn_009",
    date: "2025-12-01",
    description: "Touch n Go Reload",
    amount: 100.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_010",
    date: "2025-12-01",
    description: "Spotify Premium",
    amount: 15.9,
    type: "debit",
    category: "entertainment",
  },
  // November 2025
  {
    id: "txn_011",
    date: "2025-11-30",
    description: "GSC Cinema 1Utama",
    amount: 45.0,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_012",
    date: "2025-11-28",
    description: "Jaya Grocer",
    amount: 234.5,
    type: "debit",
    category: "food",
  },
  {
    id: "txn_013",
    date: "2025-11-25",
    description: "Celcom Postpaid",
    amount: 98.0,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_014",
    date: "2025-11-15",
    description: "iCloud Storage",
    amount: 4.9,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_015",
    date: "2025-11-10",
    description: "YouTube Premium",
    amount: 22.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_016",
    date: "2025-11-05",
    description: "Netflix Subscription",
    amount: 54.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_017",
    date: "2025-11-03",
    description: "TNB Electricity Bill",
    amount: 118.6,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_018",
    date: "2025-11-01",
    description: "Salary November",
    amount: 8500.0,
    type: "credit",
    category: "income",
  },
  {
    id: "txn_019",
    date: "2025-11-01",
    description: "Spotify Premium",
    amount: 15.9,
    type: "debit",
    category: "entertainment",
  },
  // October 2025
  {
    id: "txn_020",
    date: "2025-10-28",
    description: "Grab Unlimited Pass",
    amount: 35.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_021",
    date: "2025-10-25",
    description: "Celcom Postpaid",
    amount: 98.0,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_022",
    date: "2025-10-15",
    description: "iCloud Storage",
    amount: 4.9,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_023",
    date: "2025-10-12",
    description: "Shell Petrol Station",
    amount: 145.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_024",
    date: "2025-10-10",
    description: "YouTube Premium",
    amount: 22.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_025",
    date: "2025-10-05",
    description: "Netflix Subscription",
    amount: 49.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_026",
    date: "2025-10-03",
    description: "TNB Electricity Bill",
    amount: 132.5,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_027",
    date: "2025-10-01",
    description: "Salary October",
    amount: 8500.0,
    type: "credit",
    category: "income",
  },
  {
    id: "txn_028",
    date: "2025-10-01",
    description: "Spotify Premium",
    amount: 15.9,
    type: "debit",
    category: "entertainment",
  },
  // September 2025
  {
    id: "txn_029",
    date: "2025-09-28",
    description: "Grab Unlimited Pass",
    amount: 35.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_030",
    date: "2025-09-25",
    description: "Celcom Postpaid",
    amount: 98.0,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_031",
    date: "2025-09-15",
    description: "iCloud Storage",
    amount: 4.9,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_032",
    date: "2025-09-10",
    description: "YouTube Premium",
    amount: 17.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_033",
    date: "2025-09-05",
    description: "Netflix Subscription",
    amount: 49.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_034",
    date: "2025-09-01",
    description: "Salary September",
    amount: 8500.0,
    type: "credit",
    category: "income",
  },
  {
    id: "txn_035",
    date: "2025-09-01",
    description: "Spotify Premium",
    amount: 15.9,
    type: "debit",
    category: "entertainment",
  },
  // August 2025
  {
    id: "txn_036",
    date: "2025-08-28",
    description: "Grab Unlimited Pass",
    amount: 35.0,
    type: "debit",
    category: "transport",
  },
  {
    id: "txn_037",
    date: "2025-08-25",
    description: "Celcom Postpaid",
    amount: 98.0,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_038",
    date: "2025-08-15",
    description: "iCloud Storage",
    amount: 4.9,
    type: "debit",
    category: "utilities",
  },
  {
    id: "txn_039",
    date: "2025-08-10",
    description: "YouTube Premium",
    amount: 17.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_040",
    date: "2025-08-05",
    description: "Netflix Subscription",
    amount: 49.9,
    type: "debit",
    category: "entertainment",
  },
  {
    id: "txn_041",
    date: "2025-08-01",
    description: "Salary August",
    amount: 8500.0,
    type: "credit",
    category: "income",
  },
  {
    id: "txn_042",
    date: "2025-08-01",
    description: "Spotify Premium",
    amount: 15.9,
    type: "debit",
    category: "entertainment",
  },
];
